export enum SurgeryStatus {
  SCHEDULED = 'SCHEDULED',
  PRE_OPERATIVE = 'PRE_OPERATIVE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  POSTPONED = 'POSTPONED',
  IN_RECOVERY = 'IN_RECOVERY',
  DISCHARGED = 'DISCHARGED'
}
