export enum VisitType {
  GENERAL = 'GENERAL',
  FOLLOW_UP = 'FOLLOW_UP',
  CONSULTATION = 'CONSULTATION',
  EMERGENCY = 'EMERGENCY',
  ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
  VACCINATION = 'VACCINATION',
  DIAGNOSTIC_TEST = 'DIAGNOSTIC_TEST',
  OTHER = 'OTHER',
}
